### ISSUE TITLE
不支持1.17.1？

### ISSUE THREAD

**Issue by NoMathExpectation** [hugeBlack/McfDebugger_Mod#2]
尝试用1.17.1加载mod，结果无法加载，说这是个1.16.x的mod，能不能出一个1.17.1的mod？

**Comment by hugeBlack** [comment]
mojang在1.17对函数相关的逻辑有改动（虽然表面上看不出来），稍微过段时间吧

**Comment by hugeBlack** [comment]
1.2.1版本支持Minecraft1.17.1了，可以去release查看。不过暂时还无法查看离maxCommandChainLength用完还剩多少指令，还得想想办法。
